# Generated by Django 3.2.4 on 2021-06-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coderegistro',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
