# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/pycqa/pylint
    rev: v2.9.5
    hooks:
      - id: pylint
        args:
        - --disable=W0403,F0401,W0614,R0903
