# Generated by Django 3.2.5 on 2021-09-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='posts/photos'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
