# Generated by Django 3.2.5 on 2021-09-12 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='fav_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
